# 导航栏
nav:
  logo: /images/head.jpg
  display_title: true
  fixed: false

  # 导航栏菜单
menu:
  首页: / || fas fa-home
  归档: /archives/ || fas fa-archive
  标签: /tags/ || fas fa-tags
  分类: /categories/ || fas fa-folder-open
  关于: /about/ || fas fa-heart

# 文章 meta 信息显示
post_meta:
  page:
    date_type: created      
    date_format: date
    categories: true        
    tags: false             
    label: true
  post:
    date_type: both         
    date_format: date
    categories: true        
    tags: true            
    label: true

# 网站图标
favicon: /images/head.jpg

# 头像
avatar:
  img: /images/head.jpg
  effect: false        # 头像动画，建议关闭

# 顶部图
default_top_img: /img/3.png
index_img: /img/1.jpg
archive_img: /img/2.png
tag_img: /img/1.jpg
category_img: /img/4.jpg

# 背景图
background: /img/banner.jpg

# 代码高亮
highlight_theme: mac

# 深色模式
darkmode:
  enable: true
  button: true
  autoChangeMode: 2

# 打字机效果
subtitle:
  enable: true
  loop: true
  source: false
  sub: 
    - 欢迎来到我的博客
    - 记录技术与生活

# 本地搜索
search:
  path: search.xml
  field: post
  content: true
  format: html

# 懒加载
lazyload:
  enable: true
  native: false
  field: site
  blur: true

# 字数统计
wordcount:
  enable: true
  post_wordcount: true
  min2read: true
  total_wordcount: true

inject:
  head:
    - <link rel="stylesheet" href="/css/vinyl-player.css">
    - <style>#page-header{background-position:center 25%;}</style>


aplayerInject:
  enable: false

